name: CI

on:
  push:
    branches:
      - main
      - develop

env:
  APP_NAME: githubactions-demo
  PYTHON_VERSION: "3.10"
jobs:

  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Show GitHub context
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref }}"
          echo "Commit: ${{ github.sha }}"
          echo "Actor: ${{ github.actor }}"
      
      - name: show application configuration
        run: |
            echo "APPLICATION NAME $APP_NAME"
            echo "python version $ PYTHON_VERSION"


      - name: Run tests
        run: python -m pytest

      - name: Show Failure Message
        if: failure()
        run: echo "Test Failed"

      - name: Create a test report
        if: always()
        run: |
          echo "Test Completed" > test-result.txt

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test-result.txt

  build:
    needs: tests
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Build Docker image
        run: docker build -t githubactions-demo:v1 .